version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - portfolio

networks:
  portfolio:
    name: portfolio
    external: true
